name: arisa-genai
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - pip
  - pytorch
  - tokenizers
  - sentence-transformers
  - pandas
  - numpy
  - scikit-learn
  - nbformat 
  - plotly                    